### ISSUE TITLE
facultyDepartment taxonomy slugs don't work with wpGraphQL

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/franciscan-react#110]
To see the issue go to /english/faculty. It works then try to go to /fine-arts/faculty it does not work. It also doesn't work with any other slug that has more than one word. 

I have tried making the slug on Wordpress "finearts" instead of "fine-arts" but I still can't get any data. You can test directly with GraphiQL by using the following: 

```
query  {
      facultyDepartments(where: { name:"fine-arts" }) {
        edges {
          node {
            name
            faculty {
              edges {
                node {
                  title
                  slug
                }
              }
            }
          }
        }
      }
    }
```

**Comment by mrcreel** [comment]
Off course the Fine Arts department has to be the one that goes against the grain by removing the space in its name instead of replacing it with a hyphen like everyone else.

```
query FacultyListQuery($slug: [String]) {
  facultyDepartments(where: {slug: $slug}) {
    edges {
      node {
        slug
        name
        faculty {
          edges {
            node {
              title
              slug
            }
          }
        }
      }
    }
  }
}
```
I'm not sure if this can be fixed in the routing, but it is the exception, not the rule
