### ISSUE TITLE
Add materialUI grid components to FacultyListItem.js

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/franciscan-react#141]
On small screens, the content should display vertically, with image on top of text.

**Comment by ChrisBrownie55** [comment]
What page URL is __`<FacultyListItem>`__ used in? I know that it's used in the file _`page/faculty-list.js`_, however, when I go to _`/faculty-list`_ in my browser I get:

```
GraphQLError: Syntax Error: Invalid number, expected digit but got: "l".
```

**Comment by JesseRWeigel** [comment]
Try `/education/faculty`
