### ISSUE TITLE
Change how post types display on search page

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/franciscan-react#152]
![image](https://user-images.githubusercontent.com/11077930/43655828-26067d66-971e-11e8-8cfa-fd35e93f2f8f.png)

The post types displayed in gold colored font need to be changed.
- Any hyphens need to be changed into spaces
- The word "Page" needs to be removed

I am thinking regex may be the best way to do this, but a `.find` would work too.
Either way the changes can be made in the search.js component.

**Comment by kwitochka** [comment]
Jesse, I am trying to solve this issue. Gonna send you a pull request soon.

**Comment by JesseRWeigel** [comment]
#153
