### ISSUE TITLE
Fix changing types on the scroll in search.js

### ISSUE THREAD

**Issue by kwitochka** [fus-marcom/franciscan-react#154]
In the search when you scroll the results, you can notice how *Institute* and *Bioethics* are interchanging. You can see the example here: [Interchanging types](https://www.useloom.com/share/1748688dd8404374810832df983c6f19).  

Maybe it's not only these two types. Further examination required.

**Comment by JesseRWeigel** [comment]
After switching to Algolia for search, this doesn't seem to be happening anymore.
