### ISSUE TITLE
Use SvgIcon component

### ISSUE THREAD

**Issue by cr101** [fus-marcom/franciscan-react#16]
You might want to use the [Material-UI SvgIcon component](https://material-ui-next.com/api/svg-icon/#svgicon) for all the svg images in [AppBar.js](https://github.com/fus-marcom/franciscan-react/blob/master/components/AppBar.js) as it will give you better performance. For an example look at the source code for the [Material-Ui Docs website](https://github.com/callemall/material-ui/blob/v1-beta/docs/src/modules/components/GitHub.js)

**Comment by pantharshit00** [comment]
PR #18 closes this
