### ISSUE TITLE
Serverless Docker Deployments

### ISSUE THREAD

**Issue by cr101** [fus-marcom/franciscan-react#168]
Zeit has recently released [Serverless Docker Beta](https://zeit.co/blog/serverless-docker) which from my understanding it removes the need to have two hosting environments,  one for the frontend app and one for WordPress.

Check out the [examples](https://github.com/zeit/now-examples)

**Comment by pantharshit00** [comment]
I guess he has now switched to google app engine and a staging app is deployed to this URL https://fus-main-site.appspot.com so I think this issue is need to be get closed.
