### ISSUE TITLE
Perhaps use Flexbox

### ISSUE THREAD

**Issue by cr101** [fus-marcom/franciscan-react#17]
I wonder if it will be easier to use [Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) to align the social icons and search box in the AppBar. Perhaps look at the source code for the [Material-UI documentation website](https://github.com/callemall/material-ui/blob/069d33256004c3886d9299c8e219e724c642f6f2/docs/src/modules/components/AppFrame.js#L112) and see how they achieved that.
https://github.com/fus-marcom/franciscan-react/blob/6dfddeb6bb174dbb9ab8196015dd5af1b7a785c1/components/AppBar.js#L30

**Comment by pantharshit00** [comment]
PR #18 closes this
