### ISSUE TITLE
[feature request] Navigate to root page on logo click

### ISSUE THREAD

**Issue by MrNime** [fus-marcom/franciscan-react#29]
If you are on a random page on the site, clicking on the logo in the appbar or the drawer should bring you back to the root page.

**Comment by SebastianCApostolescu** [comment]
This is a easy to do task that you can do it by yourself and since you already have a PR open you can push this change there.

Hint: You have to use the `Link` component that `NextJS` provides.

If you need more help don't hesitate to ask!

Good luck!

**Comment by lelbil** [comment]
Hey @SebastianCApostolescu 😃 

 Where can I find the `Link` component? (I can do this if @MrNime don't mind)

**Comment by SebastianCApostolescu** [comment]
From `NextJS` [docs](https://github.com/zeit/next.js/#routing). Also an [example](https://github.com/fus-marcom/franciscan-react/blob/master/pages/page.js) from this repo.

Good Luck 😄 !

**Comment by lelbil** [comment]
Hey @MrNime , I hope you don't mind that I created PR [#30](https://github.com/fus-marcom/franciscan-react/pull/30) on this issue. I would appreciate your feedback :)

**Comment by MrNime** [comment]
I'm happy with it, it's Jesse's call in the end though :)
This gives me an idea to edit the contributing file, adding instructions for adding an upstream repository so you can keep you local copy up-to-date with what changes happen to the main repository here.

**Comment by SebastianCApostolescu** [comment]
Great idea @MrNime! Also, please make the `CONTRIBUTING.md` text in the `README` a link to the contributing file. It's bugging me off 😂

**Comment by JesseRWeigel** [comment]
PR #30 does this for the app bar (thanks @lelbil !). The same needs to be done for the drawer.
