### ISSUE TITLE
On click, the search icon in the top bar should expand to reveal a text field.

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/franciscan-react#48]

**Comment by NickyMeuleman** [comment]
Got stuck trying to implement this one. Everything went fine until I wanted to add the open/close animation.
I added an isSearchOption boolean to the state and wanted to change the value assigned to the input-field class based on that. (that boolean got flipped on search-icon-click)

Something like
```
    searchField: {
      width: this.state.isSearchOpen ? '128px' : '0px',
      transition: 'all .5s'
    }
```
The function with the style rules is not inside the component, so you can't access the state like that there.

Am I attempting to add this animation in the wrong way, how would I go about it?

**Comment by JesseRWeigel** [comment]
What if you created an "open" class and a "closed" class. The element itself would have access to state. Does this make sense?

**Comment by NickyMeuleman** [comment]
Trying this now!
