### ISSUE TITLE
Make /contact route go to a page with links to all of the department directory pages.

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/franciscan-react#51]

**Comment by angelfeliz** [comment]
Hi, this is the /contact route 

server.get('/contact/:id', (req, res) =>
    renderAndCache(req, res, '/directory', { id: req.params.id })
  )

It look like is already routing to the directory page or do you want to go to other directory page, if yes please provide the name

**Comment by JesseRWeigel** [comment]
We just need to have a page for contact and another page for all the directories. I think we set up something similar in the ci-react repo. For the News pages.

**Comment by Davidcreador** [comment]
@JesseRWeigel Hello Jesse, I want to contribute in this thread. What is the issue here? What exactly is the goal? :)

**Comment by JesseRWeigel** [comment]
Currently we have pages with urls like contact/marketing that take you to a page with contact info for the marketing department. I want a page that has the url /contact with links to all of the different contact pages. Does that make sense?

**Comment by Davidcreador** [comment]
@JesseRWeigel  Yes it does make sense. Where can I find all the contact pages you want to include in that page?

**Comment by JesseRWeigel** [comment]
@Davidcreador this page has a list of all contact pages https://www.franciscan.edu/contact/

I don't think I have the data for the main contact page transferred over yet, but the route can still be set up just like I did in the stream today for the /associate page.

**Comment by Davidcreador** [comment]
@JesseRWeigel Perfect! I have it all set up. I am pulling data from associate query but we can leave it there until the real contact info is transferred.
What do you think?
