### ISSUE TITLE
[discussion] Commit messages

### ISSUE THREAD

**Issue by NickyMeuleman** [fus-marcom/franciscan-react#61]
As mentioned by @JesseRWeigel on the stream, maybe structured commit messages would be a positive?

[Commitizen](https://commitizen.github.io/cz-cli/) seems like something that would fit if this repository goes that route, what do you all think? Other suggestions?
(reading some commitizen docs right now, only just learned of it)

**Comment by JesseRWeigel** [comment]
This looks very interesting. Does anyone have experience with Commitizen? Any reason why we shouldn't use it?

**Comment by angelfeliz** [comment]
The project of freecodecamp are using that tool. Also they have https://www.npmjs.com/package/validate-commit-msg wich we can setup with husky, we are already usign. Basically it allow to specific commit messange e.g fix: the color on the table     
It fallow the standars on http://conventionalcommits.org/

**Comment by JesseRWeigel** [comment]
@angelfeliz this sounds like a good idea

**Comment by NickyMeuleman** [comment]
@angelfeliz Do you know what the differences are with what's used as commitizen adapter for the moment `cz-conventional-changelog`? This does seem more configurable and like it would also enforce commit formatting when not commiting from commitizen, nice 😃.
The linked npm package is [deprecated](https://github.com/conventional-changelog-archived-repos/validate-commit-msg). They recommend using [commitlint](https://github.com/marionebl/commitlint) instead.

**Comment by angelfeliz** [comment]
commitlint look pretty good and we can setup a shared configuration they already have a list of option like @commitlint/config-conventional @NickyMeuleman excellent!!

**Comment by NickyMeuleman** [comment]
I am currently trying to set up commitlint.
Using the [conventional commit configuration](https://github.com/marionebl/commitlint/tree/master/@commitlint/config-conventional) which follows the rules on http://conventionalcommits.org/


`Work In Progress`
For the moment, this doesn't show you a list you can choose from while entering the type.
It appears to be more powerful than the `cz-conventional-changelog` in use now.
The one annoying thing is that you have to write `:skip` if you don't want to fill out a field (like scope or body) instead of just letting you enter.

**Comment by pantharshit00** [comment]
The new commit system is awesome. @NickyMeuleman

**Comment by NickyMeuleman** [comment]
Closing for now since the current commitizen implementation works and provides a better user experience than commitlint.
