### ISSUE TITLE
Remove babel plugin module alias when react apollo 2.1 becomes stable

### ISSUE THREAD

**Issue by pantharshit00** [fus-marcom/franciscan-react#68]
As to get beta 2.1 working I used this babel plugin. Once 2.1  hits stable we need to remove that as I am sure will be get fixed.

See #67 

Opening this issue as not to forget that.

**Comment by NickyMeuleman** [comment]
released: https://dev-blog.apollodata.com/introducing-react-apollo-2-1-c837cc23d926

**Comment by JesseRWeigel** [comment]
Thanks @NickyMeuleman ! I am reading up on this now.

**Comment by pantharshit00** [comment]
af7d989 closes this
