### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/franciscan-react#7]
We need to decide what we want to use for testing. Suggestions?

**Comment by pantharshit00** [comment]
Enzyme and storybook. Nightmare is also good

**Comment by amandeepmittal** [comment]
I think snapshot testing with Jest and Enzyme is a good fit.

**Comment by JesseRWeigel** [comment]
Thanks for the suggestions! I will look into these.

**Comment by pantharshit00** [comment]
PR #19 closes this
