### ISSUE TITLE
Implement search

### ISSUE THREAD

**Issue by JesseRWeigel** [fus-marcom/franciscan-react#74]
We need to be able to search across all post types at the same time. It will also be good to allow users to filter and sort their search a finely as is reasonable. 

I have installed a wordpress plugin that allows us to search across multiple posts types with the WP REST Api by sending a GET request like this:

```http://104.236.41.59/wp-json/wp/v2/multiple-post-type?search=catholic&type[]=post&type[]=page&type[]=admissions-page&type[]=chapel-page```

First step is just to enable a request like this for all posts types from the search fields.

After that we can work on the filters. I think the search function we used for the ci-react site should work with some modification.

**Comment by cr101** [comment]
@JesseRWeigel What's the name of the WordPress plugin that allows searching across multiple posts types with the WP REST API?

**Comment by JesseRWeigel** [comment]
@cr101 it is called WP Rest Api V2 Multiple PostTypes

**Comment by JesseRWeigel** [comment]
We should be able to direct users to pages for most search results since we will have the content type and the slug. We can create a url out of those. It may not work for everything. Still need to test it.
