### ISSUE TITLE
Update Material UI (to beta 33)

### ISSUE THREAD

**Issue by NickyMeuleman** [fus-marcom/franciscan-react#81]
Release notes: https://github.com/mui-org/material-ui/releases

Pay close attention to the breaking changes under each version that's newer than the one in use right now.

This one:
[API] Complete type to variant migration
affects the student profile card (possibly other cards as well)

**Comment by JesseRWeigel** [comment]
Thanks @NickyMeuleman ! We will update sometime soon. For the next few days I need to keep the version as is. The site needs to be ready for some presentations.

**Comment by cr101** [comment]
beta.36 was released 3 days ago

**Comment by JesseRWeigel** [comment]
Last presentation is today. After than we can update to the latest version!
