### ISSUE TITLE
Bug: Inkbar colors since MUI-update

### ISSUE THREAD

**Issue by NickyMeuleman** [fus-marcom/franciscan-react#95]
The inkbar color doesn't work anymore since the update to the newest MUI.
![chrome_2018-03-22_21-42-57](https://user-images.githubusercontent.com/30179461/37797402-039f293e-2e1a-11e8-8852-54b88c71d898.png)
(the bottom bar used to be gold)

That results in this error in the console:
![chrome_2018-03-22_21-43-56](https://user-images.githubusercontent.com/30179461/37797448-2560fcbe-2e1a-11e8-83f4-8bb9cd0bdd86.png)

Issue is related to this breaking change in MUI:
https://github.com/mui-org/material-ui/pull/10457

same thing for search-inkbar in the header

**Comment by NickyMeuleman** [comment]
Show how to do it in current version of MUI here under customized input: https://material-ui-next.com/demos/text-fields/

**Comment by JesseRWeigel** [comment]
Thank you @NickyMeuleman ! I will work on this soon.

If anyone else wants to take this one, that is OK with me too.

**Comment by JesseRWeigel** [comment]
This has been fixed!
